# Generated by Django 2.1.3 on 2021-10-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_auto_20200609_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('1', 'Unidad'), ('2', 'Otros')], max_length=20),
        ),
    ]
